#!/bin/bash

# Default directory if no argument is provided
DEFAULT_DIR="/var/www/nextcloud/data/yourusername/files"
TARGET_DIR="${1:-$DEFAULT_DIR}"
LOGFILE="/var/log/nextcloud_photo_fix.log"

# Check if the target directory exists
if [ ! -d "$TARGET_DIR" ]; then
  echo "Directory not found: $TARGET_DIR" | tee -a "$LOGFILE"
  exit 1
fi

echo "Processing directory: $TARGET_DIR" | tee -a "$LOGFILE"

# Extract Nextcloud path (e.g., yourusername/files/Photos from 2014)
NC_PATH="${TARGET_DIR#/var/www/nextcloud/data/}"
echo "Nextcloud relative path: $NC_PATH" | tee -a "$LOGFILE"

# Process EXIF metadata for images
find "$TARGET_DIR" -type f -name "*.jpg" -o -name "*.jpeg" | while read file; do
  current_date=$(exiftool -s -s -s -FileModifyDate "$file")
  original_date=$(exiftool -s -s -s -DateTimeOriginal "$file")

  if [ -n "$original_date" ] && [ "$current_date" != "$original_date" ]; then
    echo "Updating EXIF date for $file to $original_date" | tee -a "$LOGFILE"
    sudo exiftool -overwrite_original "-FileModifyDate=$original_date" "$file"
  fi
done

# Process JSON metadata
find "$TARGET_DIR" -name "*.json" -o -name "*.supplemental-m.json" | while read jsonfile; do
  basefile="${jsonfile%.supplemental-m.json}"
  basefile="${basefile%.supplemental-metadata.json}"

  if [ -f "$basefile" ]; then
    current_date=$(exiftool -s -s -s -FileModifyDate "$basefile")
    timestamp=$(jq -r '.photoTakenTime.timestamp' "$jsonfile")
    formatted_date=$(date -d @"$timestamp" "+%Y:%m:%d %H:%M:%S")

    if [ -n "$formatted_date" ] && [ "$current_date" != "$formatted_date" ]; then
      echo "Setting date for $basefile to $formatted_date" | tee -a "$LOGFILE"
      sudo exiftool -overwrite_original "-FileModifyDate=$formatted_date" "$basefile"
    fi
  fi
done

# Remove backup files generated by exiftool
sudo find "$TARGET_DIR" -name "*.jpg_original" -delete
sudo find "$TARGET_DIR" -name "*.jpeg_original" -delete
sudo find "$TARGET_DIR" -name "*.mp4_original" -delete

# Re-scan files in Nextcloud
if [ -n "$NC_PATH" ]; then
  echo "Scanning Nextcloud path: $NC_PATH" | tee -a "$LOGFILE"
  sudo -u www-data php /var/www/nextcloud/occ files:scan --path="$NC_PATH" >> "$LOGFILE" 2>&1
else
  echo "Scanning all files in Nextcloud" | tee -a "$LOGFILE"
  sudo -u www-data php /var/www/nextcloud/occ files:scan --all >> "$LOGFILE" 2>&1
fi

echo "Completed processing at $(date)" | tee -a "$LOGFILE"
